test_that("core helpers return tags", {
  expect_s3_class(block_sidebar("Item"), "shiny.tag")
  expect_s3_class(block_nav(block_nav_item("Home")), "shiny.tag")
  expect_s3_class(block_header("Header"), "shiny.tag")
  expect_s3_class(block_body("Body"), "shiny.tag")
  expect_s3_class(block_card("Body"), "shiny.tag")
  expect_s3_class(block_card_header("Header"), "shiny.tag")
  expect_s3_class(block_card_title("Title"), "shiny.tag")
  expect_s3_class(block_card_description("Description"), "shiny.tag")
  expect_s3_class(block_card_content("Content"), "shiny.tag")
  expect_s3_class(block_card_footer("Footer"), "shiny.tag")
  expect_s3_class(block_button("Button"), "shiny.tag")
  expect_s3_class(block_badge("New"), "shiny.tag")
  expect_s3_class(block_alert("Notice"), "shiny.tag")
  expect_s3_class(block_alert_title("Title"), "shiny.tag")
  expect_s3_class(block_alert_description("Body"), "shiny.tag")
  expect_s3_class(block_value_box("Title", "42"), "shiny.tag")
  expect_s3_class(block_separator(), "shiny.tag")
  expect_s3_class(block_skeleton(), "shiny.tag")
  expect_s3_class(block_spinner(), "shiny.tag")
  expect_s3_class(block_empty("Nothing here"), "shiny.tag")
  expect_s3_class(block_icon("search"), "shiny.tag")
  expect_s3_class(block_select("plan", choices = c("Free", "Pro")), "shiny.tag")
})

test_that("showcase app sources without launching", {
  app_file <- system.file("showcase", "app.R", package = "shinyblocks")
  env <- new.env(parent = globalenv())

  source(app_file, local = env, chdir = TRUE)

  expect_s3_class(env$ui, "shiny.tag.list")
  expect_type(env$server, "closure")
})
