test_that("core helpers return tags", {
  expect_s3_class(block_sidebar("Item"), "shiny.tag")
  expect_s3_class(block_nav(block_nav_item("Home")), "shiny.tag")
  expect_s3_class(block_header("Header"), "shiny.tag")
  expect_s3_class(block_body("Body"), "shiny.tag")
  expect_s3_class(block_card("Body"), "shiny.tag")
  expect_s3_class(block_card_header("Header"), "shiny.tag")
  expect_s3_class(block_card_title("Title"), "shiny.tag")
  expect_s3_class(block_card_description("Description"), "shiny.tag")
  expect_s3_class(block_card_content("Content"), "shiny.tag")
  expect_s3_class(block_card_footer("Footer"), "shiny.tag")
  expect_s3_class(block_button("Button"), "shiny.tag")
  expect_s3_class(block_badge("New"), "shiny.tag")
  expect_s3_class(block_alert("Notice"), "shiny.tag")
  expect_s3_class(block_alert_title("Title"), "shiny.tag")
  expect_s3_class(block_alert_description("Body"), "shiny.tag")
  expect_s3_class(block_value_box("Title", "42"), "shiny.tag")
  expect_s3_class(block_separator(), "shiny.tag")
  expect_s3_class(block_skeleton(), "shiny.tag")
  expect_s3_class(block_spinner(), "shiny.tag")
  expect_s3_class(block_empty("Nothing here"), "shiny.tag")
  expect_s3_class(block_icon("search"), "shiny.tag")
  expect_s3_class(block_select("plan", choices = c("Free", "Pro")), "shiny.tag")
  expect_s3_class(block_textarea("notes"), "shiny.tag")
  expect_s3_class(block_checkbox("agree", "Agree"), "shiny.tag")
  expect_s3_class(block_switch("alerts", "Alerts"), "shiny.tag")
  expect_s3_class(block_tab("Overview", "Body"), "shiny.tag")
  expect_s3_class(block_tabs(block_tab("Overview", "Body")), "shiny.tag")
  expect_s3_class(block_theme(primary = "oklch(0.5 0.2 250)"), "shiny.tag")
  expect_s3_class(block_theme(preset = "olive"), "shiny.tag")
  expect_s3_class(block_style("default"), "shinyblocks_style")
  expect_s3_class(block_dark_mode_toggle(), "shiny.tag")
})

test_that("block_page accepts a style profile", {
  page <- block_page("Body", style = block_style("default", control_height = "2.5rem"))
  expect_s3_class(page, "shiny.tag.list")
})

test_that("showcase app sources without launching", {
  app_file <- system.file("showcase", "app.R", package = "shinyblocks")
  env <- new.env(parent = globalenv())

  source(app_file, local = env, chdir = TRUE)

  expect_s3_class(env$ui, "shiny.tag.list")
  expect_type(env$server, "closure")
})
