---
title: "Card"
description: "Versatile container for grouped content."
---

```{r, include = FALSE}
library(shiny)
library(shinyblocks)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Card

Displays a card with header, content, and footer.

## Usage

```r
library(shinyblocks)

block_card(
  block_card_header(
    block_card_title("Card Title"),
    block_card_description("Card Description")
  ),
  block_card_content(
    p("Card Content")
  ),
  block_card_footer(
    p("Card Footer")
  )
)
```

## Examples

### Basic

A complete card example with all sections.

<div class="sb-component-preview">
```{r, echo=FALSE, results="asis"}
cat(as.character(block_card(
  class = "w-[350px]",
  block_card_header(
    block_card_title("Create project"),
    block_card_description("Deploy your new project in one-click.")
  ),
  block_card_content(
    p("Deploy your project to the cloud.")
  ),
  block_card_footer(
    div(class = "flex justify-between w-full",
      block_button("Cancel", variant = "outline"),
      block_button("Deploy")
    )
  )
)))
```
</div>
<div class="sb-component-code-title">Code</div>
```r
block_card(
  block_card_header(
    block_card_title("Create project"),
    block_card_description("Deploy your new project in one-click.")
  ),
  block_card_content(
    p("Deploy your project to the cloud.")
  ),
  block_card_footer(
    div(class = "flex justify-between w-full",
      block_button("Cancel", variant = "outline"),
      block_button("Deploy")
    )
  )
)
```
