---
title: "Checkbox"
description: "Toggle state for a single option."
---

```{r, include = FALSE}
library(shiny)
library(shinyblocks)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Checkbox

A control that allows the user to toggle a binary state.

## Usage

```r
library(shinyblocks)

block_checkbox("terms", label = "Accept terms and conditions")
```

## Examples

### Basic

<div class="sb-component-preview">
```{r, echo=FALSE, results="asis"}
cat(as.character(block_checkbox("terms_demo", label = "Accept terms and conditions")))
```
</div>
<div class="sb-component-code-title">Code</div>
```r
block_checkbox("terms", label = "Accept terms and conditions")
```

### With Description

<div class="sb-component-preview">
```{r, echo=FALSE, results="asis"}
cat(as.character(block_field(
  block_checkbox("marketing", label = "Marketing emails"),
  block_field_description("Receive emails about new products and features.")
)))
```
</div>
<div class="sb-component-code-title">Code</div>
```r
block_field(
  block_checkbox("marketing", label = "Marketing emails"),
  block_field_description("Receive emails about new products and features.")
)
```
