---
title: "Slider"
description: "Range selection from a scale."
---

```{r, include = FALSE}
library(shiny)
library(shinyblocks)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Slider

An input where the user selects a value from a given range.

## Usage

```r
library(shinyblocks)

block_slider("slider_id", min = 0, max = 100, value = 50)
```

## Examples

### Basic

A standard slider with default styling.

<div class="sb-component-preview">
```{r, echo=FALSE, results="asis"}
cat(as.character(block_slider("slider_demo", min = 0, max = 100, value = 33)))
```
</div>
<div class="sb-component-code-title">Code</div>
```r
block_slider("slider_demo", min = 0, max = 100, value = 33)
```

### With Label

Sliders are often used with labels to indicate the range or purpose.

<div class="sb-component-preview">
```{r, echo=FALSE, results="asis"}
cat(as.character(block_field(
  block_field_label("Volume"),
  block_slider("volume", min = 0, max = 100, value = 80)
)))
```
</div>
<div class="sb-component-code-title">Code</div>
```r
block_field(
  block_field_label("Volume"),
  block_slider("volume", min = 0, max = 100, value = 80)
)
```
