#!/usr/bin/env Rscript

spec_dir <- file.path("docs", "component-specs")
spec_files <- list.files(spec_dir, pattern = "\\.md$", full.names = TRUE)
spec_files <- spec_files[
  !basename(spec_files) %in% c("README.md", "_template.md", "SCREENSHOT-QUEUE.md")
]
args <- commandArgs(trailingOnly = TRUE)

extract_screenshot <- function(path) {
  lines <- readLines(path, warn = FALSE)
  hit <- grep("^!\\[[^]]*\\]\\(_screenshots/[^)]+\\)$", lines, value = TRUE)
  if (!length(hit)) {
    return(NA_character_)
  }

  sub("^!\\[[^]]*\\]\\((_screenshots/[^)]+)\\)$", "\\1", hit[[1]])
}

extract_reference <- function(path) {
  lines <- readLines(path, warn = FALSE)
  hit <- grep("^> Shadcn reference: <https?://[^>]+>$", lines, value = TRUE)
  if (!length(hit)) {
    return(NA_character_)
  }

  sub("^> Shadcn reference: <(https?://[^>]+)>$", "\\1", hit[[1]])
}

coalesce <- function(x, y) {
  if (is.null(x) || length(x) == 0L || all(is.na(x))) {
    return(y)
  }
  x
}

records <- lapply(spec_files, function(path) {
  rel <- extract_screenshot(path)
  list(
    spec = basename(path),
    reference = extract_reference(path),
    screenshot = rel,
    exists = !is.na(rel) && file.exists(file.path(spec_dir, rel))
  )
})

missing <- Filter(function(x) !isTRUE(x$exists), records)

cat("\ncomponent-spec screenshot inventory\n")
cat(strrep("-", 60), "\n", sep = "")

if ("--markdown" %in% args) {
  output_idx <- match("--output", args)
  output_path <- if (!is.na(output_idx) && output_idx < length(args)) {
    args[[output_idx + 1L]]
  } else {
    file.path(spec_dir, "SCREENSHOT-QUEUE.md")
  }

  lines <- c(
    "# Screenshot Queue",
    "",
    "Generated by `tools/spec-screenshots.R --markdown`.",
    "",
    sprintf("- spec docs scanned: `%d`", length(records)),
    sprintf("- missing screenshots: `%d`", length(missing)),
    "",
    "| Spec | Shadcn reference | Screenshot path | Status |",
    "| --- | --- | --- | --- |"
  )

  for (item in records) {
    lines <- c(
      lines,
      sprintf(
        "| `%s` | %s | `%s` | %s |",
        item$spec,
        coalesce(item$reference, "n/a"),
        coalesce(item$screenshot, "n/a"),
        if (isTRUE(item$exists)) "captured" else "missing"
      )
    )
  }

  writeLines(lines, output_path)
  cat(sprintf("Wrote markdown queue to %s\n", output_path))
}
cat(sprintf("spec docs scanned: %d\n", length(records)))
cat(sprintf("missing screenshots: %d\n", length(missing)))

if (length(missing)) {
  cat("\nPending captures:\n")
  for (item in missing) {
    cat(sprintf(
      "  - %-24s %s\n",
      item$spec,
      coalesce(item$screenshot, "(no image ref)")
    ))
  }
} else {
  cat("\nAll component specs reference a committed screenshot.\n")
}

cat(strrep("-", 60), "\n", sep = "")
