#!/usr/bin/env Rscript

spec_dir <- file.path("docs", "component-specs")
spec_files <- list.files(spec_dir, pattern = "\\.md$", full.names = TRUE)
spec_files <- spec_files[
  !basename(spec_files) %in% c("README.md", "_template.md", "SCREENSHOT-QUEUE.md")
]
args <- commandArgs(trailingOnly = TRUE)

extract_screenshot <- function(path) {
  lines <- readLines(path, warn = FALSE)
  hit <- grep("^!\\[[^]]*\\]\\(_screenshots/[^)]+\\)$", lines, value = TRUE)
  if (!length(hit)) {
    return(NA_character_)
  }

  sub("^!\\[[^]]*\\]\\((_screenshots/[^)]+)\\)$", "\\1", hit[[1]])
}

extract_reference <- function(path) {
  lines <- readLines(path, warn = FALSE)
  hit <- grep("^> Shadcn reference: <https?://[^>]+>$", lines, value = TRUE)
  if (!length(hit)) {
    return(NA_character_)
  }

  sub("^> Shadcn reference: <(https?://[^>]+)>$", "\\1", hit[[1]])
}

extract_capture_note <- function(path) {
  lines <- readLines(path, warn = FALSE)
  idx <- grep("^## Reference screenshot\\s*$", lines)
  if (!length(idx)) {
    return(NA_character_)
  }

  tail <- lines[(idx[[1]] + 1L):length(lines)]
  tail <- trimws(tail)
  tail <- tail[nzchar(tail)]
  tail <- tail[!grepl("^!\\[[^]]*\\]\\(", tail)]
  if (!length(tail)) {
    return(NA_character_)
  }

  tail[[1L]]
}

coalesce <- function(x, y) {
  if (is.null(x) || length(x) == 0L || all(is.na(x))) {
    return(y)
  }
  x
}

capture_priority <- function(spec_name) {
  seed <- c("button.md", "card.md", "select.md", "tabs.md")
  high_risk <- c(
    "checkbox.md",
    "switch.md",
    "textarea.md",
    "dark-mode-toggle.md",
    "badge.md",
    "nav-item.md",
    "sidebar.md"
  )

  if (spec_name %in% seed) {
    return("seed")
  }
  if (spec_name %in% high_risk) {
    return("high-risk")
  }
  "remaining"
}

capture_status <- function(screenshot_exists, capture_note) {
  if (!isTRUE(screenshot_exists)) {
    return("missing")
  }
  if (is.na(capture_note) || grepl("^Capture pending", capture_note)) {
    return("captured-undated")
  }
  if (grepl("\\b20[0-9]{2}-[0-9]{2}-[0-9]{2}\\b", capture_note)) {
    return("captured-dated")
  }
  "captured-undated"
}

build_records <- function(paths) {
  records <- lapply(paths, function(path) {
    rel <- extract_screenshot(path)
    exists <- !is.na(rel) && file.exists(file.path(spec_dir, rel))
    note <- extract_capture_note(path)
    list(
      spec = basename(path),
      reference = extract_reference(path),
      priority = capture_priority(basename(path)),
      screenshot = rel,
      exists = exists,
      capture_note = note,
      status = capture_status(exists, note)
    )
  })

  priority_levels <- c("seed", "high-risk", "remaining")
  records[order(
    match(vapply(records, `[[`, character(1), "priority"), priority_levels),
    vapply(records, `[[`, character(1), "spec")
  )]
}

output_idx <- match("--output", args)
output_path <- if (!is.na(output_idx) && output_idx < length(args)) {
  args[[output_idx + 1L]]
} else {
  file.path(spec_dir, "SCREENSHOT-QUEUE.md")
}

stamp_idx <- match("--stamp-date", args)
stamp_date <- if (!is.na(stamp_idx) && stamp_idx < length(args)) {
  args[[stamp_idx + 1L]]
} else {
  NA_character_
}

if (!is.na(stamp_date) && !grepl("^20[0-9]{2}-[0-9]{2}-[0-9]{2}$", stamp_date)) {
  stop("--stamp-date must be in YYYY-MM-DD format.", call. = FALSE)
}

stamp_captured_notes <- function(path, date) {
  lines <- readLines(path, warn = FALSE)
  ref_idx <- grep("^## Reference screenshot\\s*$", lines)
  ref <- extract_reference(path)
  shot <- extract_screenshot(path)
  if (is.na(shot)) {
    shot <- sprintf("_screenshots/%s.png", sub("\\.md$", "", basename(path)))
  }

  if (!length(ref_idx) || is.na(shot)) {
    return(invisible(FALSE))
  }

  note <- if (!is.na(ref)) {
    c(
      sprintf("Captured from <%s> on %s.", ref, date),
      "Refresh and update the date whenever shadcn updates the canonical look."
    )
  } else {
    c(
      sprintf("Captured from the local shinyblocks showcase on %s.", date),
      "Refresh and update the date whenever the shinyblocks reference treatment changes."
    )
  }

  image_alt <- sub("\\.md$", "", basename(path))
  image_alt <- gsub("-", " ", image_alt)
  image_alt <- paste0(
    toupper(substr(image_alt, 1L, 1L)),
    substr(image_alt, 2L, nchar(image_alt))
  )

  lines <- c(
    lines[seq_len(ref_idx[[1L]])],
    "",
    sprintf("![%s](%s)", image_alt, shot),
    "",
    note
  )
  writeLines(lines, path)
  invisible(TRUE)
}

if (!is.na(stamp_date)) {
  for (path in spec_files) {
    rel <- extract_screenshot(path)
    if (is.na(rel)) {
      rel <- sprintf("_screenshots/%s.png", sub("\\.md$", "", basename(path)))
    }
    if (file.exists(file.path(spec_dir, rel))) {
      stamp_captured_notes(path, stamp_date)
    }
  }
}

records <- build_records(spec_files)
missing <- Filter(function(x) identical(x$status, "missing"), records)

markdown_lines <- c(
  "# Screenshot Queue",
  "",
  "Generated by `tools/spec-screenshots.R --markdown`.",
  "",
  sprintf("- spec docs scanned: `%d`", length(records)),
  sprintf("- missing screenshots: `%d`", length(missing)),
  "",
  "| Priority | Spec | Shadcn reference | Screenshot path | Status |",
  "| --- | --- | --- | --- | --- |"
)

for (item in records) {
  markdown_lines <- c(
    markdown_lines,
    sprintf(
      "| `%s` | `%s` | %s | `%s` | %s |",
      item$priority,
      item$spec,
      coalesce(item$reference, "n/a"),
      coalesce(item$screenshot, "n/a"),
      item$status
    )
  )
}

cat("\ncomponent-spec screenshot inventory\n")
cat(strrep("-", 60), "\n", sep = "")

if ("--markdown" %in% args) {
  writeLines(markdown_lines, output_path)
  cat(sprintf("Wrote markdown queue to %s\n", output_path))
}

if ("--check-markdown" %in% args) {
  committed <- if (file.exists(output_path)) {
    readLines(output_path, warn = FALSE)
  } else {
    character()
  }

  if (!identical(committed, markdown_lines)) {
    cat(sprintf("FAIL: %s is stale. Run make spec-screenshots-md.\n", output_path))
    quit(status = 1L)
  }

  cat(sprintf("OK: %s is up to date.\n", output_path))
}

cat(sprintf("spec docs scanned: %d\n", length(records)))
cat(sprintf("missing screenshots: %d\n", length(missing)))
cat(sprintf(
  "captured but undated: %d\n",
  sum(vapply(records, function(x) identical(x$status, "captured-undated"), logical(1)))
))
cat(sprintf(
  "captured and dated: %d\n",
  sum(vapply(records, function(x) identical(x$status, "captured-dated"), logical(1)))
))

if (length(missing)) {
  cat("\nPending captures:\n")
  for (item in missing) {
    cat(sprintf(
      "  - %-10s %-24s %s\n",
      item$priority,
      item$spec,
      coalesce(item$screenshot, "(no image ref)")
    ))
  }
} else {
  cat("\nAll component specs reference a committed screenshot.\n")
}

undated <- Filter(function(x) identical(x$status, "captured-undated"), records)
if (length(undated)) {
  cat("\nCaptured but still missing date note:\n")
  for (item in undated) {
    cat(sprintf(
      "  - %-10s %-24s %s\n",
      item$priority,
      item$spec,
      coalesce(item$screenshot, "(no image ref)")
    ))
  }
}

cat(strrep("-", 60), "\n", sep = "")
